### ISSUE TITLE
Nerodomos title paveikslėlis

### ISSUE THREAD

**Issue by andiukas** [algirdasc/hass-eso#1]
Labas,
Nerodomas title paveiksliukas:  https://brands.home-assistant.io/_/eso/icon.png
Taip pat kiek objektų integracija turi, nes pas mane tik vienas atsiranda update objektas.

**Comment by algirdasc** [comment]
Labas. 
Title paveikslelio ir nerodys, nes logotipų nekontributinau į brands repositoriją.

Dėl objektų nelabai supratau. Jei skaitei README, ten parasyta, kad default'u imamas tik consumption. Jei reikia objekto gamybos - reikia nustatyti `returned: true`. Butu aiškiau, jeigu pridėtum eso integracijos konfigą.

**Comment by andiukas** [comment]
![16881142828012668358022827556361](https://github.com/algirdasc/hass-eso/assets/44068098/c9eca641-ccdd-4406-9756-5ec2991b10ce)

**Comment by andiukas** [comment]
Bus minčių, kas čia blogai ?

**Comment by algirdasc** [comment]
Nelabai suprantu klausimo. Gal galima tiksliai paaiskinti, kas neveikia ar kas yra blogai?

**Comment by andiukas** [comment]
> Nelabai suprantu klausimo. Gal galima tiksliai paaiskinti, kas neveikia ar kas yra blogai?

Klausimas, kiek objektų gaunama ? Nes dabar tik gaunu update objektą eso_energy_statistics_import_update ir jokių duomenų niekur nerandu.
