### ISSUE TITLE
Tarifai diena ir naktis

### ISSUE THREAD

**Issue by andiukas** [algirdasc/hass-eso#13]
Sveiki,
O gal eitų pridėti dieninius ir naktinius ESO ir nepriklausomo tiekėjo tarifus. Nes dabar skaičiuojama tik vienu tarifu, bei jei turimas dviejų tarifų skaitiklis, tai dedamosios ten kažkiek skiriaisi. Aišku čia reiktų aprašyti, kad prasideda diena ir kada baigiasi, bei naktis kada prasideda ir baigiasi, bei įvertinti vasaros ir žiemos laiką, kai naktinis tarifas ir dieninis tarifai valanda persislenka. Na bet gal įmanoma ;)

**Comment by algirdasc** [comment]
Nelabai supratau. Šitas komponentas traukia informaciją iš ESO, jeigu eso nepateikia informacijos dviems tarifais, šitas komponentas to irgi nepadarys.
