### ISSUE TITLE
Neberodo gražintų į tinklą reikšmių nuo nuo 08.29 dienos

### ISSUE THREAD

**Issue by HeLLmiXZ** [algirdasc/hass-eso#14]
Neberodo gražintų į tinklą reikšmių nuo nuo 08.29 dienos. Sunaudotą rodo gerai. Grafike matosi kad minusuoja grąžintą nes vertes 0 ties tom valandom kur gamino, bet grąžintų verčių nėra. 
Loge toki meta:

Logger: homeassistant
Source: custom_components/eso/__init__.py:100
Integration: ESO Energy Consumption (documentation, issues)
First occurred: 19:41:20 (1 occurrences)
Last logged: 19:41:20

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eso/__init__.py", line 108, in async_first_start
    await async_import_generation(datetime.now())
  File "/config/custom_components/eso/__init__.py", line 100, in async_import_generation
    if obj[CONF_PRICE_ENTITY]:
       ~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'price_entity'

**Comment by HeLLmiXZ** [comment]
![Screenshot_20240906_195158_Home Assistant](https://github.com/user-attachments/assets/96649340-b9d9-4c05-bd5b-12be5df35759)
![Screenshot_20240906_195148_Home Assistant](https://github.com/user-attachments/assets/e1a350f1-ce79-4c53-bed5-ac22a92bd508)
`

**Comment by algirdasc** [comment]
Gal galetum atsinaujinti i naujausia versija ir pasakyti, ar problema islieka?

**Comment by HeLLmiXZ** [comment]
Jop veikia dabar. Naujinau ikeldamas failus, per HACS nerode kad yra naujinys. Tik 09.09 diena spyglys didelis, toliau nuo 09.10 dienos rodo gerai. Ačiū 🙂
![Screenshot_20240917_211210_Home Assistant](https://github.com/user-attachments/assets/56377fa2-8094-4034-b39a-16a96d2bc02b)
![Screenshot_20240917_211201_Home Assistant](https://github.com/user-attachments/assets/e23c60b2-ebce-4163-98d7-51dcfd5c435e)

**Comment by HeLLmiXZ** [comment]
Dar klausimas prie progos🙂  kiek dienų traukia info? Nes žiūriu yra tarpas, kurio nežpildė. Nuo 08.29 iki 09.09
![Screenshot_20240917_212441_Home Assistant](https://github.com/user-attachments/assets/ba03c961-063c-4a77-866b-b8acec17b27a)
