### ISSUE TITLE
Energy usage time offset

### ISSUE THREAD

**Issue by Citizen07** [algirdasc/hass-eso#15]
I am using your ESO integration as HA Energy usage source. Consumption looks to be 1 hour ahead compared to other sensors that track energy:
![Screenshot_2024-09-14-20-29-37-829_io homeassistant companion android](https://github.com/user-attachments/assets/5fefcefc-ea5b-41bf-92dc-8ef2e5637d55)

I can provide more examples if needed. 
Before updating to latest version there was no offset and it was matching.

**Comment by algirdasc** [comment]
Could you update to newest version and report if the issue is fixed?

**Comment by Citizen07** [comment]
Updated to eabfcd1 commit, should historic data update automatically?
One additional note: consumption from previous day stops at 23:00.  I think this is related.
![image](https://github.com/user-attachments/assets/40604507-b677-4105-96a7-5db0b01c3962)

By the way I am located in Kaunas, my current time zone in home assistant is UTC+3.

There is data from ESO page from same day for comparison:
![image](https://github.com/user-attachments/assets/a0572568-817e-428b-a712-9ef8de1cf6df)

There is -1 hour offset in home assistant energy tab compared to ESO.

**Comment by algirdasc** [comment]
Thanks for info, I'll debug it and push fix to master
