### ISSUE TITLE
Nepasileidzia meta error’a

### ISSUE THREAD

**Issue by TITAS1533** [algirdasc/hass-eso#2]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eso/eso_client.py:56 
Integration: ESO Energy Consumption (documentation, issues) 
First occurred: 00:15:34 (1 occurrences) 
Last logged: 00:15:34

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/eso/__init__.py", line 102, in async_first_start
    await async_import_generation(datetime.now())
  File "/config/custom_components/eso/__init__.py", line 86, in async_import_generation
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eso/eso_client.py", line 102, in fetch_consumption_data
    data = self.fetch(obj, date)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eso/eso_client.py", line 56, in fetch
    raise Exception("Form ID not found. Check your credentials.")
Exception: Form ID not found. Check your credentials.

visi prisijungimai kaip ir tesingi ,gal yra minciu kas negerai?

**Comment by algirdasc** [comment]
Butu gerai, kad pertikrintum ar tikrai geri prisijungimai, nes panasu, kad neuzkrauna ESO suvartojimo istorijos puslapio.

**Comment by kasparasl** [comment]
Gal yra koks update dėl šito issue? nes man meta lygiai tokį patį errora :|

**Comment by algirdasc** [comment]
Pridėjau išsamesnį loginimą. Atsinaujinkite integraciją, įjunkite debug loginimą integracijai:
```logger:
  default: error
  logs: 
    custom_components.eso: debug
```

Prisekite klaidos logą čia.

**Comment by kasparasl** [comment]
Ok dabar radau problemą. Buvo viršuje rodomas modalas atnaujinti kontaktus. kai jį rodo scriptas nepaima formos ir rodo klaidą :)
