### ISSUE TITLE
Returned data is not fetched

### ISSUE THREAD

**Issue by justinasjaronis** [algirdasc/hass-eso#4]
[I](url) have configured my account and consumption data works well, however I dont get any returned electricity data. Here is output of debug log:

https://pastebin.com/Y7pHxFAN

**Comment by algirdasc** [comment]
```
2023-10-18 16:38:54.775 DEBUG (MainThread) [custom_components.eso] Statistic ID for ESO is eso:energy_returned_12345
2023-10-18 16:38:54.775 ERROR (MainThread) [custom_components.eso] Received empty generation data for eso:energy_returned_1234629
```

Šitoje vietoje kažkaip nesutampa. Gal gali parodyti, kaip susikonfigūravai integraciją?

**Comment by justinasjaronis** [comment]
čia į tą 12345* galima nekreipt dėmesio, aš čia anonimizavau duomenis taip :) 

konfigūracija tokia:

eso:
  username: <email>
  password: 12345
  objects:
    - name: ESO
      id: 12345
      returned: True

**Comment by algirdasc** [comment]
Ok, pameginsiu patestuoti, gal mano bug'as kažkur likęs.

**Comment by algirdasc** [comment]
Išleidau bugfixą - prie progos atsinaujink integraciją.

**Comment by justinasjaronis** [comment]
Sveikas, super, suveikė.
O aš galvoju gal periodą už kurį fetchina duomenis, galima į kokį config variable ištraukt? Aš galvoju kad labai cool būtų retroperspektyviai bent už šiuos metus nusisrėbt.

**Comment by algirdasc** [comment]
Teoriškai galima, praktiškai - sunkiau.

`eso_client.py` faile, 73 eilutėje  `"active_date_value": date.strftime("%Y-%m-%d 00:00"),`. Vietoj `date.strftime("%Y-%m-%d 00:00")` įrašęs norimą datą, pvz: `"active_date_value": "2023-01-07 00:00:00,` nusipūstum pirmos sausio savaitės duomenis. 

Bet HA tokio duomenų "įterpimo" greičiausiai nesupras dėl statistikos skaičiavimo logikos. HA duomenis skaičiuoja nuo 0. Jei bandysi įrašyti duomenis už ankstesnį laikotarpį, tai HA gali nesuprasti tokio skaitliuko pakeitimo ir statistika išsikraipytų. Pirmiau reikėtų ištrinti integracijos sugneruotą statistiką, bet čia jau reikėtų rankomis kištis tiesiai į duombazę ir čia jau aš negaliu atsakyti už padarytą žalą. 

Jei vis tik niežti pirštai išbandyti, tai prieš viską darant siulyčiau pasidaryti DB kopiją arba analogišką situaciją pasidaryti ant tuščio HA instance'o.

**Comment by justinasjaronis** [comment]
Tai aš manau kad paprasčiausia tiesiog kitaip pavadinti objektą. Tada sukurs naują sensorių. Bet manau čia ne man vienam aktualu, tai iškelt į configą šią datą manau daug kam gali padėt :)

**Comment by justinasjaronis** [comment]
aaaai bet aš supratau, čia reikia po savaitę pūst. Tai čia kurkas daugiau logikos nei configą įdėt. tai nevermind

**Comment by algirdasc** [comment]
Tai ilgainiui užsipildys už metus :) Istorinius duomenis visada galima ir ESO savitarnoje rasti :)
