### ISSUE TITLE
shouldn't returned energy be positive?

### ISSUE THREAD

**Issue by justinasjaronis** [algirdasc/hass-eso#5]
After last commit I'm getting returned energy as well however I think to suite Home assistant logic it should be positive instead of negative number. Because now it sums up to generation.
![Screenshot from 2023-11-04 15-03-05](https://github.com/algirdasc/hass-eso/assets/4047890/6c1f9b41-fb37-44e7-b8f1-365d970cfa8c)

**Comment by algirdasc** [comment]
Fixed in latest commit. Thank you.
