### ISSUE TITLE
Elektros kainos apskaiciavimas - kaip?:)

### ISSUE THREAD

**Issue by alekspere** [algirdasc/hass-eso#7]
Aciu uz integracija - pastaciau kavos ;)
Taip pat naudoju https://github.com/custom-components/nordpool apskaiciuoti elektros tarifa.
Kaip siuos du galima butu apjungti kad HA rodytu galutine elektros kaina dashboard'e?

Neleidzia pasirinkti "Use an entity with current price" varianto.

![image](https://github.com/algirdasc/hass-eso/assets/3525215/ebae6ef7-4a65-49f3-98b7-ff520dccc74e)

**Comment by alekspere** [comment]
Padariau pradine patobulinimo versija su kainos skaiciavimu. https://github.com/alekspere/hass-eso/tree/costs_calculation

**Comment by algirdasc** [comment]
Sveikas, gal gali pakurti PR? Manau praverstu ir kitiems tokie pakeitimai.

**Comment by alekspere** [comment]
Norejau sulaukti pilno menesio saskaitos ir palyginti su HA.
Radau netiksluma - HA duomenys per 1 val prasilenkia su ESO ir su ENEFIT (mano tiekejas). Padariau pataisyma.
Pakoreguosiu README (idesiu konfiguracijos pavyzdi kainos skaiciavimui) ir pakelsiu PR.

**Comment by algirdasc** [comment]
Super, aciu labai :)
