### ISSUE TITLE
no new entities after installation

### ISSUE THREAD

**Issue by tomass0328** [algirdasc/hass-eso#9]
Instaliavau ESO per HACS, įdėjau setingus į configuration.yaml, restartavau HA, bet jokių naujų entity neatsiranda. Ką darau ne taip?

**Comment by algirdasc** [comment]
Entity ir naujų ir neturi atsirasti. Tavo suvartojimo statistika matysis prie Energy dashboard'o (https://www.home-assistant.io/docs/energy/)

**Comment by tomass0328** [comment]
a, mat kaip, ačiū :)

**Comment by tomass0328** [comment]
į eneregy dashboard susidėjau, bet ir reduced ir consumed rodo 0...

**Comment by algirdasc** [comment]
Eso pateikia duomenis už praėjusią dieną, todėl šios dienos generavimą matysi tik rytoj.

**Comment by tomass0328** [comment]
integracija padaryta vakar, tai šiandien jau lyg ir turėjau matyti

**Comment by algirdasc** [comment]
Na aš neatspėsiu kodėl nerodo. Patikrink ar ESO yra informacija už vakar dieną, patikrintk HA log'us, patikrink ar gerai viska pasetupinai.

**Comment by pac-lt** [comment]
ar eso prisijungus nepraso atnaujinti kontaktu ?
jei objekto ID nesutampa su URL matomu - naudoti id is URL
